### ISSUE TITLE
Backpropogation2005Xu&Wang

### ISSUE THREAD

**Issue by WOLVS** [IPASC/standardised-image-reconstruction#1]
Image reconstruction task to reproduce universal back-project algorithm 
 Universal back-projection algorithm for photoacoustic computed tomography
Journal: Physical Review (1167 citations)
DOI: https://doi.org/10.1103/PhysRevE.71.016706

The paper describes the principle and mathematical foundation of the back-projection algorithm (also referred to as “delay-and-sum” throughout the literature for the discrete implementation of the algorithm).
The algorithm has been implemented numerous times in different variations and with different additional features and considerations, some of which are available open-source.

**Comment by jgroehl** [comment]
We have integrated a baseline delay and sum back-projection for arbitrary detection geometries now.
We are still missing typical pre- and postprocessing steps throughout the literature.
Maybe we can use this task to collect a list of pre-and post-processing steps/algorithms that are frequently used with PAI?

**Comment by jgroehl** [comment]
Since backprojection is integrated into ` main`, I think we can close this issue.
