### ISSUE TITLE
fnumber and pDAS implementation

### ISSUE THREAD

**Issue by fvarray** [IPASC/standardised-image-reconstruction#2]
Insertion of the fnumber in the DAS

**Comment by jgroehl** [comment]
Hi @fvarray, I have merged your pull request into the main branch.

**Comment by jgroehl** [comment]
FNumber, pdas, and sign coherence factor (SCF) are implemented now and integrated into ` main`.
Cal we close this @fvarray ?

**Comment by fvarray** [comment]
issue closed and codes merges into main
