### ISSUE TITLE
FFT-based2007Jaeger

### ISSUE THREAD

**Issue by MengjieSHI** [IPASC/standardised-image-reconstruction#3]
image reconstruction task to reproduce a Fourier transform-based reconstruction algorithm. Journal: Inverse Problems (117 citations) DOI: http://dx.doi.org/10.1088/0266-5611/23/6/S05

The paper describes a Fourier transform-based reconstruction algorithm. The authors use a custom-tailored regularised interpolation method since they consider traditional interpolation methods to be inadequate. The authors state that the algorithm is closely related to convolution interpolation algorithms commonly used for Fourier reconstruction in MRI, CT, etc. One crucial advantage is that the complexity of the method is (N log N) since it makes use of a Fourier transform to trivialise the necessary convolution.

**Comment by jgroehl** [comment]
Is now merged into master, so we can close this issue :)
