### ISSUE TITLE
Non-negative detector positions 

### ISSUE THREAD

**Issue by MengjieSHI** [IPASC/standardised-image-reconstruction#35]
Dear all, 

I simulated a string phantom using SIMPA and am trying to compare the reconstruction algorithms with IPASC by simply loading the saved hdf5 files. I noticed the[ reconstruction results](https://github.com/MengjieSHI/standardised-image-reconstruction/blob/5a48995d1bfc0ed9f0db3b9c3e8ce5acf622e800/test_results.png) of DAS and DMAS got cropped, which was caused by the mismatch of the detector positions between my simulation (containing negative coordinates) and the initialization in [reconstruction_base.py ](https://github.com/IPASC/standardised-image-reconstruction/blob/99474107e26d212a7a2abfb57c0f5e8e3fdb9a8f/image_reconstruction/reconstruction_algorithms/reconstruction_base.py#L53). 

The [script](https://github.com/MengjieSHI/standardised-image-reconstruction/blob/211cf72a48ca3e93061e1c335b0b8b80b503c5b2/evaluate_string_phantom.py ) to reproduce the errors. (needed [ipasc hdf5 files](https://github.com/MengjieSHI/standardised-image-reconstruction/blob/211cf72a48ca3e93061e1c335b0b8b80b503c5b2/CompletePipelineExample_4711.hdf5 ) and [hdf5 file](https://github.com/MengjieSHI/standardised-image-reconstruction/blob/211cf72a48ca3e93061e1c335b0b8b80b503c5b2/CompletePipelineExample_4711_ipasc.hdf5
))

The results seem [corrected](https://github.com/MengjieSHI/standardised-image-reconstruction/blob/5a48995d1bfc0ed9f0db3b9c3e8ce5acf622e800/test_results_nonnegative.png) by commenting out the[ line 55-57](https://github.com/IPASC/standardised-image-reconstruction/blob/99474107e26d212a7a2abfb57c0f5e8e3fdb9a8f/image_reconstruction/reconstruction_algorithms/reconstruction_base.py#L55), but I am wondering the reason for using the non-negative coordinates here. 

Many thanks! 
Mengjie:)

**Comment by jgroehl** [comment]
Thanks for looking into this @MengjieSHI !!
Could you be so kind as to open a pull request with the lines commented out?

I think I added these by accident as I played around with non-negativity at some point...

Also, what is happening with the other FFT-based reconstruction? @jpoimala, do you mind taking a look at it?

Thanks!
Janek

**Comment by jgroehl** [comment]
I've merged the pull request!
